---
title: "Washington D.C. Property Price Analysis and Prediction"
output:
  html_document:
    df_print: paged
---

## Overview

1. Purpose
2. Dataset
3. Methodology
4. Modelling

## Preparation

[Metadata](https://www.arcgis.com/sharing/rest/content/items/c5fb3fbe4c694a59a6eef7bf5f8bc49a/info/metadata/metadata.xml?format=default&output=html)

```{r warning=FALSE, message=FALSE}
library(dplyr)      # df manipulation
library(ggplot2)    # graphical plot
library(GGally)     # ggplot extension
library(grid)       # grid plot
library(gridExtra)  # grid extension
library(knitr)      # pretty print
library(kableExtra) # print styling
library(stringr)    # handle strings
library(ggmap)      # geographical map
library(bitops)     # bitwise operation
library(corrplot)   # correlation matrix
library(car)        # VIF
library(lmtest)     # non-constant variance test
library(MASS)       # AIC
library(leaps)      # model selection
library(DAAG)       # cross-validation

select <- dplyr::select
```

### __Dataset Overview__

```{r}
# read the dataset
house.price <- read.csv('DC_Properties.csv', na.strings = c("", "NA"))
```

```{r}
# show column structures
str(house.price)
```

```{r}
# ZIPCODE, USECODE are more of categorical data
house.price$ZIPCODE <- as.factor(house.price$ZIPCODE)
house.price$USECODE <- as.factor(house.price$USECODE)
house.price$CENSUS_TRACT <- as.factor(house.price$CENSUS_TRACT)
```

```{r}
# show first a few rows 
kable(head(house.price, n = 10)) %>%
  kable_styling() %>%
  scroll_box(width = "100%", height = "500px")
```

### __Preprocessing: *Rows of Interest*__

```{r}
cat("Number of Condominiums:",
    pull(count(house.price[house.price$SOURCE == 'Condominium', ])))
```

```{r}
cat("[Residential PRICE Summary]\n")
print(summary(house.price[house.price$SOURCE == "Residential", 'PRICE']))

cat("\n[Condominium PRICE Summary]\n")
print(summary(house.price[house.price$SOURCE == "Condominium", 'PRICE']))
```

```{r}
# narrow it down to 'Residential'
house.price <- house.price[house.price$SOURCE == "Residential", ]
```

```{r}
house.price$SALEDATE <- substr(house.price$SALEDATE, 0, 10)
house.price$SALEDATE <- as.Date(house.price$SALEDATE)

sale.year <- as.numeric(substr(house.price[, "SALEDATE"], 0, 4))
sale.year <- sale.year[!is.na(sale.year)]
hist(sale.year,
     breaks = c(-Inf, seq(1990, 2018, 1)),
     xlim = c(1990, 2018),
     main = "Sales by Year",
     xlab = "Year",
     border = 'blue', col = 'green',
     prob = T)
axis(side = 1, at = c(2015, 2018))
lines(density(sale.year), col = 'red')
```

```{r}
quantile(sale.year, probs = seq(0, 1, 0.1))
```

```{r}
# drop sales made before 2016.01.01.
house.price <- subset(house.price, SALEDATE > as.Date("2015-12-31"))
```


### __Dependent Variable: *Price*__

```{r}
# drop rows with price as NA
house.price <- house.price[complete.cases(house.price[ , "PRICE"]), ]
```

```{r warning=FALSE}
# histogram independent variable "Price"
ggplot(house.price, aes(x = PRICE)) + 
  geom_histogram(binwidth = 20000,
                 fill = "blue",
                 alpha = .25) +
  labs(title = "Washington D.C House Price Histogram") +
  labs(x = "Price", y = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlim(c(0, 2000000)) +
  geom_vline(aes(xintercept = mean(PRICE), color = "mean"),
             linetype = "dashed", size = 1) +
  geom_vline(aes(xintercept = median(PRICE), color = "median"),
             linetype = "dashed", size = 1) +
  scale_color_manual(name = "", values = c(mean = "pink", median = "green"))
```

```{r}
summary(house.price$PRICE)
```


### __On the Map__

```{r include=FALSE}
sbbox <- make_bbox(lon = house.price$LONGITUDE, lat = house.price$LATITUDE, f = 0.1)
dc_map <- get_stamenmap(sbbox, zoom = 12, maptype = "toner-lite")

price_group <- c(seq(0, 1000000, by = 200000), Inf)
price_label <- c("<200k", "<400k", "<600k", "<800k", "<1mil", ">1mil")
```

```{r warning=FALSE}
ggmap(dc_map) + 
  geom_point(data = house.price, 
             aes(LONGITUDE, LATITUDE,
                 color = cut(PRICE, price_group)), 
             size = 0.3, alpha = 0.3) +
  labs(title = "Washington D.C House Price Heat Map") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_color_brewer(palette = "Oranges",
                     name = "Price Range",
                     labels = price_label)
```


### __Handle Outliers__

```{r}
lowerq <- quantile(house.price$PRICE)[2]
upperq <- quantile(house.price$PRICE)[4]
iqr <- upperq - lowerq
lower.threshold <- lowerq - (iqr*1.5)
upper.threshold <- upperq + (iqr*1.5)

cat("Lower Outlier Threshold:", lower.threshold,
    "\nUpper Outlier Threshold:", upper.threshold)
```

```{r}
house.price <- house.price[house.price$PRICE < upper.threshold, ]
```


### __Preprocessing: *Drop Variables*__

```{r}
# drop redundant or single-value variables
house.price <- select(house.price, -c("X.1", "CITY", "STATE", "X", "Y", 
                                      "SOURCE", "SALEDATE"))
```

```{r}
# count NA for each variable
na_count <- sapply(house.price, function(y) {
    sum(length(which(is.na(y))))
  })

# all the variables with NA's
na_count <- na_count[na_count != 0]
# variable and the number of NA's
print(na_count)
```

```{r}
# drop geographical variables except for WARD
house.price <- select(house.price, -c("ZIPCODE", "USECODE", "SQUARE", "NATIONALGRID",
                                      "ASSESSMENT_NBHD", "ASSESSMENT_SUBNBHD", 
                                      "CENSUS_BLOCK", "CENSUS_TRACT",
                                      "QUADRANT", "FULLADDRESS",
                                      "LONGITUDE", "LATITUDE"))

# drop empty variables
house.price <- select(house.price, -c("CMPLX_NUM", "LIVING_GBA"))
```

```{r}
# transform YR_RMDL by encoding into Yes or No
house.price$RMDL <- ifelse(is.na(house.price$YR_RMDL), "N", "Y")
```

```{r}
# fine tuning
cat("GIS values:")
print(levels(house.price$GIS_LAST_MOD_DTTM))
house.price <- select(house.price, -c("GIS_LAST_MOD_DTTM", "YR_RMDL"))

# drop small number of NA's (AYB, STORIES...)
house.price <- house.price[complete.cases(house.price), ]
```


------

## __Correlation Analysis__

### __Numerical Variables and Multicollinearity__

```{r}
numeric_cols <- names(select_if(house.price, is.numeric))
print(numeric_cols)
```

```{r}
corr <- cor(house.price[, numeric_cols])
corrplot.mixed(corr, number.cex = .75, tl.pos = "lt")
```

```{r}
# drop unrelated variables
house.price <- subset(house.price, select = -c(SALE_NUM, BLDG_NUM, NUM_UNITS, 
                                               KITCHENS, LANDAREA))
```

```{r}
# test for multicollinearity of numerical variables
VIF.model <- lm(PRICE ~ BATHRM + HF_BATHRM + ROOMS + BEDRM + 
                  AYB + EYB + STORIES + GBA + FIREPLACES, 
                data = house.price)
cat("[VIF with All]\n")
print(vif(VIF.model))
```

```{r}
# final correaltion table
numeric_cols <- names(select_if(house.price, is.numeric))
corr <- cor(house.price[, numeric_cols])
corrplot.mixed(corr, number.cex = .75, tl.pos = "lt")
```


### __Categorical Variables__

```{r}
categorical_cols <- names(house.price)[!names(house.price) %in% numeric_cols]
print(categorical_cols)
```

```{r}
# number of unique values in each categorical variable
str(apply(house.price[, categorical_cols], 2, function(x) unique(x)))
```

```{r}
# fix '0' values in AC
cat("Number of '0's in AC:", pull(count(house.price[house.price$AC == '0', ])))
house.price[house.price$AC == '0', 'AC'] <- "N"
```


------

## Plotting and Feature Selection

### __Scatter Plot__

```{r}
house.price_scatter <- function(var, x_start, x_lim) {
  ggplot(house.price, aes_string(var, "PRICE", fill = var)) +
    geom_point(color = "darkgreen", shape = 1, alpha = 0.1, 
               size = 0.2, position = "jitter") +
    geom_smooth(span = 5, method = lm) +
    ggtitle(toString(var)) + xlab("") +
    theme(legend.position="none") +
    scale_x_continuous(limits = c(x_start, x_lim)) +
    scale_y_continuous(limits = c(0, 1750000), 
                       breaks = seq(0, 1750000, 250000))
}
```

```{r warning=FALSE}
BATHRM <- house.price_scatter("BATHRM", 0, 8)
HF_BATHRM <- house.price_scatter("HF_BATHRM", 0, 4)
BEDRM <- house.price_scatter("BEDRM", 0, 8)
ROOMS <- house.price_scatter("ROOMS", 0, 15)

grid.arrange(BATHRM, HF_BATHRM, BEDRM, ROOMS,
             ncol = 2, nrow = 2)
```

```{r}
AYB <- house.price_scatter("AYB", 1930, 2020)
EYB <- house.price_scatter("EYB", 1930, 2020)
STORIES <- house.price_scatter("STORIES", 0, 10)
FIREPLACES <- house.price_scatter("FIREPLACES", 0, 5)


grid.arrange(AYB, EYB, STORIES, FIREPLACES,
             ncol = 2, nrow = 2)
```

```{r}
ggplot(house.price, aes(x = GBA, y = PRICE)) +
  geom_point(alpha = 0.1) + 
  geom_smooth() +
  ggtitle("GBA") + xlab("") +
  scale_x_continuous(limits = c(0, 6000),
                     breaks = seq(0, 6000, 1000)) +
  scale_y_continuous(limits = c(0, 1750000), 
                     breaks = seq(0, 1750000, 250000))
```


```{r}
# linear model with room variables
Numeric.lm <- lm(PRICE ~ BATHRM + HF_BATHRM + BEDRM + ROOMS +
              AYB + EYB + STORIES + FIREPLACES + GBA,
            data = house.price)

# constant variance tests
print(bptest(Numeric.lm))
print(ncvTest(Numeric.lm))
```

```{r}
# box-cox
bc <- boxCox(Numeric.lm)
lambda <- bc$x[which.max(bc$y)]
cat("Lambda for Transformation:", lambda)
```

```{r}
# transformation to sqrt
house.price$PRICE_TRANS <- sqrt(house.price$PRICE)

# price-sqrt histogram
ggplot(house.price, aes(x = PRICE_TRANS)) + 
  geom_histogram(aes(y = ..density..), 
                 binwidth = 20, fill = "blue", alpha = 0.25) +
  geom_density(fill = "pink", alpha = 0.25) +
  labs(title = "Washington D.C House Price SQRT") +
  labs(x = "Price_sqrt", y = "Density") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_vline(aes(xintercept = mean(PRICE_TRANS), color = "mean"), size = 0.5) +
  geom_vline(aes(xintercept = median(PRICE_TRANS), color = "median"),
             linetype = "dashed", size = 0.5) +
  scale_x_continuous(limits = c(0, 1500)) +
  scale_color_manual(name = "", values = c(mean = "red", median = "blue")) +
  stat_function(fun = dnorm, args = list(
    mean = mean(house.price$PRICE_TRANS), sd = sd(house.price$PRICE_TRANS)),
    linetype = "dashed")
```

```{r}
# final correlations with PRICE
X_col <- names(select_if(house.price, is.numeric))
X_col <- X_col[X_col != "PRICE_TRANS"]
cat("[Price-Sqrt vs. X Variables Correlation]\n")
print(cor(house.price[, X_col], house.price$PRICE_TRANS))
```


### __Box Plot: *Categorical Variables*__

```{r}
house.price_boxplot <- function(var, x.angle) {
  ggplot(house.price, aes_string(var, "PRICE_TRANS", fill = var)) +
    geom_boxplot(outlier.colour = "black", 
                 outlier.shape = 16, 
                 outlier.size = 1) +
    geom_hline(aes(yintercept = median(PRICE_TRANS)), 
               color = 'gray', linetype = "dashed", size = 0.5) +
    ggtitle(toString(var)) + xlab("") +
    theme(legend.position="none",
          axis.text.x = element_text(angle = x.angle, hjust = 1))
}
```

```{r}
lay <- rbind(c(1, 2, 3),
             c(4, 4, 5))
grid.arrange(grobs = list(house.price_boxplot("AC", 0), 
                          house.price_boxplot("RMDL", 0), 
                          house.price_boxplot("QUALIFIED", 0), 
                          house.price_boxplot("HEAT", 90),
                          house.price_boxplot("WARD", 90)),
             heights = c(0.4, 0.6),
             layout_matrix = lay)
```

```{r}
# AC '0' to 'Y'
house.price[house.price$AC == '0', "AC"] <- 'Y'

# drop HEAT
# house.price <- select(house.price, -HEAT)

# reduce wards to three types
# house.price$WARD <- ifelse(house.price$WARD %in% c('Ward 2', 'Ward 3'), 
#                            'Ward 2/3', as.character(house.price$WARD))
# house.price$WARD <- ifelse(house.price$WARD %in% c('Ward 7', 'Ward 8'), 
#                            'Ward 7/8', as.character(house.price$WARD))
# house.price$WARD <- ifelse(!house.price$WARD %in% c('Ward 2/3', 'Ward 7/8'), 
#                            'Ward 3/4/5/6', as.character(house.price$WARD))
```

```{r}
grid.arrange(house.price_boxplot("STYLE", 90),
             house.price_boxplot("STRUCT", 90),
             ncol = 2)
```

```{r}
# Style is same as Story, Struct is ambiguous
# house.price <- select(house.price, -c("STYLE", "STRUCT"))
```

```{r}
grid.arrange(house.price_boxplot("CNDTN", 90),
             house.price_boxplot("GRADE", 90), 
             ncol = 2)
```

```{r}
# cat("[Grade counts]\n")
# print(summary(house.price$GRADE))
# cat("\n[Condition counts]\n")
# print(summary(house.price$CNDTN))
# 
# # Grade: above-avg / avg / fair vs. rest
# house.price$GRADE <- ifelse(house.price$GRADE %in% 
#                         c("Above Average", "Average", "Fair Quality"), 
#                         "Average", "High")
# 
# # Condition: avg / fair / poor vs. rest
# house.price$CNDTN <- ifelse(house.price$CNDTN %in% 
#                         c("Average", "Fair", "Poor"), "Bad", "Good")
```


```{r}
house.price_boxplot("EXTWALL", 90)
```

[brick vs. wood](http://www.massrealty.com/articles/brick-homes-vs-wood-homes)
[stucco](https://en.wikipedia.org/wiki/Stucco)

```{r}
# cat("[Exterior wall counts]\n")
# print(summary(house.price$EXTWALL))
# 
# house.price$EXTWALL <- ifelse(house.price$EXTWALL %in% 
#                           c("Brick Veneer", "Brick/Stone", "Brick/Stucco", "Hardboard", 
#                             "Stone", "Stone/Stucco", "Stucco Block", "Wood Siding"), 
#                           "Premium", "Normal")
```

```{r}
grid.arrange(house.price_boxplot("INTWALL", 90), 
             house.price_boxplot("ROOF", 90), 
             ncol = 2)
```

```{r}
# drop Interior


# Roof: cheap vs. expensive
# cat("[Roof counts]\n")
# print(summary(house.price$ROOF))
# 
# house.price$ROOF <- ifelse(house.price$ROOF %in% 
#                           c("Clay Tile", "Neopren", "Slate"), 
#                           "Expensive", "Cheap")
```


------

## Modeling and Analysis

### __Linear Model__

```{r}
house.price <- select(house.price, -PRICE)
house.lm <- lm(PRICE_TRANS ~ .,data = house.price)
summary(house.lm)
```

```{r}
anova(house.lm)
```


```{r}
plot(house.lm)
```

```{r}
# influential observations
print(house.price[row.names(house.price) %in% 
    c(21, 4550, 18569, 24841, 48266, 80226), c("ROOMS", "GBA", "PRICE_TRANS")])

# drop influential observations
house.price <- house.price[!row.names(house.price) %in%
    c(21, 4550, 18569, 24841, 48266, 80226), ]
```

```{r}
ggplot(house.lm, aes(.resid)) + 
  geom_density(fill = "pink", color = "red", alpha = 0.5) +
  stat_function(fun = dnorm, args = list(mean = mean(resid(house.lm)), 
                                         sd = sd(resid(house.lm))),
                linetype = "dashed", geom = "area", alpha = 0.2) +
  xlab("Price Square Root Residuals") + ylab("Density") +
  ggtitle("Residual Plot")
```

```{r}
# forward selection
# house.lm <- regsubsets(PRICE_TRANS ~ BATHRM + HF_BATHRM + BEDRM + 
#                          AYB + CENSUS_TRACT +
#                          QUALIFIED + SOURCE + WARD, 
#                        data = house.price, 
#                        method = c("seqrep"))
# 
# lm_summary <- summary(house.lm)
# lm_summary$adjr2
```

```{r}
# stepwise selection
# house.step.lm <- stepAIC(house.lm, direction = "backward")
# summary(house.step.lm)
```

```{r}
# cross validation
# cv.lm(data = house.price, form.lm = house.lm, m = 3)
```


### __Residual Analysis__

```{r}
# house.stdresi = rstandard(house.lm)
# plot(house.price$PRICE, house.stdresi)
```


------

## Prediction with Adjusted Model

```{r}
# ridge regression

```


------

## References

[kable](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)
[Mapping](http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html#)
[ggmap Github](https://github.com/dkahle/ggmap)
[ggmap stamen](https://rdrr.io/cran/ggmap/man/get_stamenmap.html)
[corrplot](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html)
[type of apply](https://www.guru99.com/r-apply-sapply-tapply.html)
[Linear Regression Example](http://r-statistics.co/Linear-Regression.html)
[Scatter Plot](http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/)
[Outlier](https://www.r-bloggers.com/outlier-detection-and-treatment-with-r/)
[Boxplot](http://www.sthda.com/english/wiki/ggplot2-box-plot-quick-start-guide-r-software-and-data-visualization)
[VIF](http://www.scriptwarp.com/warppls/pubs/Kock_Lynn_2012.pdf)
[leaps](https://rdrr.io/cran/leaps/man/regsubsets.html)
[Diagnosis & Variable Selection](https://www.statmethods.net/stats/regression.html)
[Q-Q Plot Interpretation](https://stats.stackexchange.com/questions/101274/how-to-interpret-a-qq-plot)
[Diagnostic Plots](https://data.library.virginia.edu/diagnostic-plots/)